services:
  postgresql:
    image: postgres:15
    container_name: caching-service-postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=caching_service
    ports:
      - 9432:5432
